# This list should probably come from a config file in due course
available_setchks=[
    'CHK20_INCORR_FMT_SCTID', 
    'CHK02_IDS_IN_RELEASE', 
    'CHK01_APPROP_SCTID', 
    'CHK06_DEF_EXCL_FILTER',
    'CHK05_UNRECC_HIERARCH',
    'CHK12_MIXED_TAGS',
    'CHK03_TERM_CONGRUENCE', 
    'CHK22_DUPLICATE_REFS',
    'CHK04_INACTIVES_ENTRY',
    'CHK08_IMPLIED_INACTIVES',
    'CHK10_MISSING_CONCEPTS',
    'CHK14_MANY_CLAUSES',
    'CHK51_SUGGESTS_DUAL_SCT',
    ]